validates:
  email:
    regex: \A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z
    length: 255
link:
  rails_help: http://www.railstutorial.org/help
  rails_book: http://www.railstutorial.org/book
  rails_home: http://www.railstutorial.org/
digits:
  digit_6: 6
img:
  size_50: 50
  size_80: 80
page_10: 10
